### PR TITLE
Updated Reactive Streams to RC3

### PR DESCRIPTION
**Pull request by rozza**
[Review on Reviewable](https://reviewable.io/reviews/rozza/mongo-java-driver-reactivestreams/11)

### CODE REVIEW

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11)

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java, line 202 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj5z3yoYIjFoA1TrWJT)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java#L202)):</sup>
This is going TDocument as well if you lgtm my CR.

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java, line 224 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj5zD6FVECXSfji7vUo)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java#L224)):</sup>
This one too

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java, line 341 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj5zJ0lLjXiZ9c-4saX)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java#L341)):</sup>
Remove all occurrences in javadoc of: This can be of any type for which a {@code Codec} is registered
As it's no longer true.

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java, line 480 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj5zaXUKMgkyftWg4Lj)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java#L480)):</sup>
I've been debating whether this should go to BsonDocument, even though it's awkward to use.  What do you think?

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/MongoDatabase.java, line 110 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj5zujUq9z_Ce26M7Q-)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/MongoDatabase.java#L110)):</sup>
Same here: BsonDocument?  Rather than privilege the Document class?

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/Success.java, line 21 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj6-SLLOaGyAgfFwuCg)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/Success.java#L21)):</sup>
Just a thought: No @since tags in this project?  I just noticed it for the first time.

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/Success.java, line 22 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj6-adKk1l5wg44HiL8)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/Success.java#L22)):</sup>
This is ugly, but I don't have any better ideas.

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/Success.java, line 23 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj6-NYyeOOp41SFF7oq)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/Success.java#L23)):</sup>
Requires a Javadoc comment, no?  Is checkstyle not enforcing this?

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11)

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java, line 341 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj5zJ0lLjXiZ9c-4saX)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java#L341)):</sup>
Done.

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java, line 480 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj5zaXUKMgkyftWg4Lj)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/MongoCollection.java#L480)):</sup>
Document won out I think

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/Success.java, line 21 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj6-SLLOaGyAgfFwuCg)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/Success.java#L21)):</sup>
The ones that were there were all @since 3.0.  I have updated to @since 1.0 
Anyway to enforce via checkstyle?

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/Success.java, line 23 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj6-NYyeOOp41SFF7oq)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/Success.java#L23)):</sup>
Checkstyle doesn't enforce it  - but have added

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11)

---

<sup>**[driver/src/main/com/mongodb/reactivestreams/client/Success.java, line 23 [r1]](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11#-Jj6-SLLOaGyAgfFwuCg)** ([raw file](https://github.com/rozza/mongo-java-driver-reactivestreams/blob/66528c4512f8ec4b184f248d601bf9419c81ca7e/driver/src/main/com/mongodb/reactivestreams/client/Success.java#L23)):</sup>
Perhaps if we write a custom module, but not worth it right now.

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver-reactivestreams/11)

---

LGTM

---

**Comment by rozza** [comment]
Rebased and merged

**Pull request closed without merging**
